package edu.sjsu.cmpe275.lab2.entities;

// Generated Nov 2, 2015 9:04:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElements;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Person generated by hbm2java
 */

@XmlRootElement(name = "person")
@Entity
@Table(name = "Person", catalog = "CMPE275_LAB2")
public class Person implements java.io.Serializable {

	private long personId;
	private String firstName;
	private String lastName;
	private String email;
	private String description;

	@Transient
	@Embedded
	private Address address;

	private Organization organization;
	
	private List<Person> friends=  new ArrayList<Person>();

	public Person() {
	}

	public Person(long personid, String firstName, String lastName,String email) {
		this.personId=personid;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email=email;
	}

	public Person(String firstName, String lastName, String email,
			String description, Address address, Organization organization) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.description = description;
		this.address = address;
		this.organization = organization;
	}

	@XmlElement
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PersonID", unique = true, nullable = false)
	public long getPersonId() {
		return this.personId;
	}

	public void setPersonId(long personId) {
		this.personId = personId;
	}

	@XmlElement
	@Column(name = "FirstName", nullable = false, length = 30)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@XmlElement
	@Column(name = "LastName", nullable = false, length = 30)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@XmlElement
	@Column(name = "Email", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@XmlElement
	@Column(name = "Description", length = 30)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@XmlElement
	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	
	@XmlElementWrapper
	@XmlElement(name="friend")
	@JsonIgnore 
	@ManyToMany(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
	@JoinTable(name="Friendship",
	 joinColumns=@JoinColumn(name="PersonID"),
	 inverseJoinColumns=@JoinColumn(name="FriendID")
	)	
	public List<Person> getFriends() {
		System.out.println("getFriends: "+friends.size());
		return friends;
	}

	public void setFriends(List<Person> friends) {
		
		System.out.println("Before param Friends: "+friends.size());
		System.out.println("Before setFriends: "+this.friends.size());
		this.friends = friends;
		System.out.println("After setFriends: "+this.friends.size());
	}

	
	@XmlElement
	@ManyToOne(cascade=CascadeType.PERSIST)
	@JoinColumn(name = "organizationId")
	public Organization getOrganization() {
		return organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

}
